In [1]:
import pandas as pd
from api_keys import weather_api_key
import requests

cab_rides = pd.read_csv("cab_rides.csv/cab_rides.csv")
cab_rides.head()

,distance,cab_type,time_stamp,destination,source,price,surge_multiplier,id,product_id,name
0,0.44,Lyft,1544952607890,North Station,Haymarket Square,5.0,1.0,424553bb-7174-41ea-aeb4-fe06d4f4b9d7,lyft_line,Shared
1,0.44,Lyft,1543284023677,North Station,Haymarket Square,11.0,1.0,4bd23055-6827-41c6-b23b-3c491f24e74d,lyft_premier,Lux
2,0.44,Lyft,1543366822198,North Station,Haymarket Square,7.0,1.0,981a3613-77af-4620-a42a-0c0866077d1e,lyft,Lyft
3,0.44,Lyft,1543553582749,North Station,Haymarket Square,26.0,1.0,c2d88af2-d278-4bfd-a8d0-29ca77cc5512,lyft_luxsuv,Lux Black XL
4,0.44,Lyft,1543463360223,North Station,Haymarket Square,9.0,1.0,e0126e1f-8ca9-4f2e-82b3-50505a09db9a,lyft_plus,Lyft XL

In [2]:
uber_rides_data = cab_rides.loc[cab_rides["cab_type"] == "Uber"]
uber_rides_data.head()

,distance,cab_type,time_stamp,destination,source,price,surge_multiplier,id,product_id,name
12,1.11,Uber,1543615981179,West End,North End,12.0,1.0,009e9c53-074d-43cf-aef2-0fbc7a47ed3d,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
13,1.11,Uber,1544698211014,West End,North End,16.0,1.0,23f145da-f0c1-4d1f-a184-496bc003a7db,6c84fd89-3f11-4782-9b50-97c468b19529,Black
14,1.11,Uber,1544728503935,West End,North End,7.5,1.0,357559cb-8c58-4278-a41a-e33b2e0997a3,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
15,1.11,Uber,1545004511430,West End,North End,7.5,1.0,50ef1165-9d23-416c-a65c-18906207b295,9a0e7b09-b92b-4c41-9779-2ad22b4d779d,WAV
16,1.11,Uber,1544748007961,West End,North End,26.0,1.0,91c4861c-1780-42b0-bca1-bbd64a422cc3,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV

In [3]:
uber_rides_data["name"].unique()

array(['UberXL', 'Black', 'UberX', 'WAV', 'Black SUV', 'UberPool', 'Taxi'],
      dtype=object)

In [4]:
uber_rides = uber_rides_data[["id", "distance", "source", "destination", "price", "time_stamp", "name"]]
uber_rides.dropna(inplace = True)
uber_rides.set_index("id", inplace = True)
uber_rides.head()
uber_rides.to_csv("uber_rides.csv")

C:\Users\omoto\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [10]:
import pprint
time_stamp = uber_rides["time_stamp"]

cloudiness = []
humidity = []
max_temp = []
wind_speed = []
weather = []

#for timestamp in time_stamp:
   # try:
url = f"http://history.openweathermap.org/data/2.5/history/city?q=boston&type=hour&start=1544952607890&cnt=1&appid=8e80b4ddcad3e83aecb2a877c0200e6c"
weather_response = requests.get(url).json()
pprint.pprint(weather_response)
#cloudiness.append(weather_response["list"][0]["clouds"]["all"])
#humidity.append(weather_response["list"][0]["main"]["humidity"])
#max_temp.append(weather_response["list"][0]["main"]["temp_max"])
#wind_speed.append(weather_response["list"][0]["wind"]["speed"])
#weather.append(weather_response["list"][0]["weather"][0]["description"])
   # except:
       # print("City not found. Skipping...")
        
#weather_data = pd.DataFrame({"Cloudiness": cloudiness, "Humidity": humidity, "Max Temp": max_temp, "Wind Speed": wind_speed})
#weather_data.head()

{'cod': 401,
 'message': 'Invalid API key. Please see '
            'http://openweathermap.org/faq#error401 for more info.'}

In [72]:
boston_weather = pd.read_csv("boston-weather.csv")
#boston_weather_nov18 = boston_weather.loc[(boston_weather["Year"] == 2018)]
#boston_weather.tail()

date = boston_weather["Day"]
year = []
month = []

for day in date.tolist():
    split_date = day.split()
    month.append(split_date[1])
    year.append(split_date[2])

    
boston_weather["Month"] = month
boston_weather["Year"] = year
boston_weather.tail(50)

boston_weather_dec18 = boston_weather.loc[(boston_weather["Year"] == "2018") & (boston_weather["Month"] == "dec")]
cleaned_boston_weather_dec18 = boston_weather_dec18.replace("T", "0.01")
cleaned_boston_weather_dec18

,Day,High(°F),Low(°F),Precip.(inch),Snow(inch),Snowdepth(inch),Month,Year
1429,1 dec 2018,45.0,35.1,0.00,0.00,-,dec,2018
1430,2 dec 2018,51.1,41.0,0.75,0.00,-,dec,2018
1431,3 dec 2018,57.9,44.1,0.01,0.00,-,dec,2018
1432,4 dec 2018,44.1,27.1,0.00,0.00,-,dec,2018
1433,5 dec 2018,36.0,25.2,0.00,0.00,-,dec,2018
1434,6 dec 2018,42.1,30.2,0.01,0.01,-,dec,2018
1435,7 dec 2018,39.9,26.2,0.00,0.00,-,dec,2018
1436,8 dec 2018,31.1,20.1,0.00,0.00,-,dec,2018
1437,9 dec 2018,37.0,23.2,0.00,0.00,-,dec,2018
1438,10 dec 2018,39.0,26.2,0.00,0.00,-,dec,2018
1439,11 dec 2018,37.9,23.2,0.00,0.00,-,dec,2018
1440,12 dec 2018,39.0,24.3,0.00,0.00,-,dec,2018
1441,13 dec 2018,35.1,21.2,0.00,0.00,-,dec,2018
1442,14 dec 2018,46.0,29.1,0.00,0.00,-,dec,2018
1443,15 dec 2018,55.0,39.9,0.00,0.00,-,dec,2018
1444,16 dec 2018,45.0,41.0,0.54,0.00,-,dec,2018
1445,17 dec 2018,43.0,36.0,0.04,0.01,-,dec,2018
1446,18 dec 2018,39.0,25.2,0.02,0.12,-,dec,2018
1447,19 dec 2018,42.1,24.3,0.00,0.00,-,dec,2018
1448,20 dec 2018,50.0,32.0,0.00,0.00,-,dec,2018
1449,21 dec 2018,64.9,43.0,0.61,0.00,-,dec,2018
1450,22 dec 2018,55.9,37.0,0.02,0.00,-,dec,2018
1451,23 dec 2018,43.0,33.1,0.00,0.00,-,dec,2018
1452,24 dec 2018,39.0,32.0,0.01,0.01,-,dec,2018
1453,25 dec 2018,39.0,29.1,0.00,0.00,-,dec,2018
1454,26 dec 2018,39.9,26.2,0.00,0.00,-,dec,2018
1455,27 dec 2018,37.9,30.2,0.00,0.00,-,dec,2018
1456,28 dec 2018,57.0,34.0,0.33,0.00,-,dec,2018
1457,29 dec 2018,54.0,32.0,0.00,0.00,-,dec,2018
1458,30 dec 2018,34.0,26.2,0.00,-,-,dec,2018
1459,31 dec 2018,-,-,-,-,-,dec,2018

In [49]:
import datetime
time_stamp = uber_rides["time_stamp"]


for timestamp in time_stamp:
     new_time = str(datetime.datetime.fromtimestamp(timestamp/1000).strftime('%Y-%m-%d'))

print(new_time)
uber_rides["new_time"] = new_time
uber_rides.head()

2018-12-01

C:\Users\omoto\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,distance,source,destination,price,time_stamp,name,new_time
id,,,,,,,
009e9c53-074d-43cf-aef2-0fbc7a47ed3d,1.11,North End,West End,12.0,1543615981179,UberXL,2018-12-01
23f145da-f0c1-4d1f-a184-496bc003a7db,1.11,North End,West End,16.0,1544698211014,Black,2018-12-01
357559cb-8c58-4278-a41a-e33b2e0997a3,1.11,North End,West End,7.5,1544728503935,UberX,2018-12-01
50ef1165-9d23-416c-a65c-18906207b295,1.11,North End,West End,7.5,1545004511430,WAV,2018-12-01
91c4861c-1780-42b0-bca1-bbd64a422cc3,1.11,North End,West End,26.0,1544748007961,Black SUV,2018-12-01

In [64]:
uber_date = uber_rides["new_time"]
uber_year = []
uber_month = []

for uber_day in uber_date.tolist():
    split_uber_date = uber_day.split("-")
    uber_month.append(split_uber_date[1])
    uber_year.append(split_uber_date[0])
    
    
uber_rides["Month"] = uber_month
uber_rides["Year"] = uber_year
uber_rides.head()

C:\Users\omoto\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\omoto\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':

,distance,source,destination,price,time_stamp,name,new_time,Month,Year
id,,,,,,,,,
009e9c53-074d-43cf-aef2-0fbc7a47ed3d,1.11,North End,West End,12.0,1543615981179,UberXL,2018-12-01,12,2018
23f145da-f0c1-4d1f-a184-496bc003a7db,1.11,North End,West End,16.0,1544698211014,Black,2018-12-01,12,2018
357559cb-8c58-4278-a41a-e33b2e0997a3,1.11,North End,West End,7.5,1544728503935,UberX,2018-12-01,12,2018
50ef1165-9d23-416c-a65c-18906207b295,1.11,North End,West End,7.5,1545004511430,WAV,2018-12-01,12,2018
91c4861c-1780-42b0-bca1-bbd64a422cc3,1.11,North End,West End,26.0,1544748007961,Black SUV,2018-12-01,12,2018

In [73]:
dec18_rides = uber_rides.loc[(uber_rides["Month"] == "12") & (uber_rides["Year"] == "2018")]
dec18_rides

,distance,source,destination,price,time_stamp,name,new_time,Month,Year
id,,,,,,,,,
009e9c53-074d-43cf-aef2-0fbc7a47ed3d,1.11,North End,West End,12.0,1543615981179,UberXL,2018-12-01,12,2018
23f145da-f0c1-4d1f-a184-496bc003a7db,1.11,North End,West End,16.0,1544698211014,Black,2018-12-01,12,2018
357559cb-8c58-4278-a41a-e33b2e0997a3,1.11,North End,West End,7.5,1544728503935,UberX,2018-12-01,12,2018
50ef1165-9d23-416c-a65c-18906207b295,1.11,North End,West End,7.5,1545004511430,WAV,2018-12-01,12,2018
91c4861c-1780-42b0-bca1-bbd64a422cc3,1.11,North End,West End,26.0,1544748007961,Black SUV,2018-12-01,12,2018
...,...,...,...,...,...,...,...,...,...
353e6566-b272-479e-a9c6-98bd6cb23f25,1.00,West End,North End,9.5,1543708385534,WAV,2018-12-01,12,2018
616d3611-1820-450a-9845-a9ff304a4842,1.00,West End,North End,13.0,1543708385534,UberXL,2018-12-01,12,2018
633a3fc3-1f86-4b9e-9d48-2b7132112341,1.00,West End,North End,9.5,1543708385534,UberX,2018-12-01,12,2018
727e5f07-a96b-4ad1-a2c7-9abc3ad55b4e,1.00,West End,North End,27.0,1543708385534,Black SUV,2018-12-01,12,2018
e7fdc087-fe86-40a5-a3c3-3b2a8badcbda,1.00,West End,North End,10.0,1543708385534,UberPool,2018-12-01,12,2018

In [ ]:
cleaned_boston_weather_nov18 = boston_weather_nov18.replace("T", "0.01")
cleaned_boston_weather_nov18

In [ ]:
uber_rides_data["destination"].nunique()

In [ ]:
uber_rides_data["source"].nunique()

In [ ]:
destination = uber_rides_data["destination"]

In [ ]:
source = uber_rides_data["source"]

location = pd.concat([source, destination])
location

In [ ]:
uber_map = pd.DataFrame(location.unique())
#uber_map = pd.DataFrame(uber_rides_data["source"].unique())

In [ ]:
uber_map

In [ ]:
uber_map = uber_map.rename(columns={0: "location"})
uber_map["lat"] = ""
uber_map["long"] = ""
uber_map